version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/news_aggregator
    depends_on:
      - db
    networks:
      - news-network

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=news_aggregator
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - news-network

  redis:
    image: redis:6
    ports:
      - "6379:6379"
    networks:
      - news-network

networks:
  news-network:
    driver: bridge

volumes:
  postgres-data: