spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/news_aggregator
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=500,expireAfterWrite=300s

news:
  api:
    key: YOUR_NEWS_API_KEY
    base-url: https://newsapi.org/v2

jwt:
  secret: 0syuPP2ZlNJKild1bfaN83SwUEB7j6P4jpiNYzUv1RQ=
  expiration: 86400000

